routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::get('history', 'TransactionController@history')->name('history');
    Route::get('balance', 'UserController@getBalance')->name('balance');
    Route::get('newTransaction', 'TransactionController@create')->name('newTransaction');
    Route::get('duplicate/{transaction}', 'TransactionController@duplicate')->name('duplicate');
    Route::post('transaction', 'TransactionController@store')->name('transaction');

    Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => 'admin'], function () {
        //Users
        Route::get('users', 'UserController@index')->name('users');
        Route::get('users/{user}/edit', 'UserController@edit')->name('user.edit');
        Route::delete('users/{user}', 'UserController@destroy')->name('user.ban');
        Route::post('users/{id}', 'UserController@restore')->name('user.restore');
        Route::put('users/{user}', 'UserController@update')->name('user.update');

        //Transactions
        Route::get('transactions', 'TransactionController@index')->name('transactions');
        Route::delete('transactions/{transaction}', 'TransactionController@destroy')->name('transactions.cancel');
    });
});

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTransactionRequest;
use Illuminate\Support\Facades\DB;
use App\Transaction;
use App\User;

class TransactionController extends Controller
{
    /**
     * Show the list of all transactions.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $transactions = Transaction::withTrashed()->get();
        return view('admin.transactions.index', compact('transactions'));
    }

    /**
     * Show the history of user transactions.
     *
     * @return \Illuminate\Http\Response
     */
    public function history()
    {
        $transactions = auth()->user()->transactions;
        return view('history', compact('transactions'));
    }

    /**
     * Show the form for creating a new transaction.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::where('id', '!=', auth()->user()->id)->orderBy('name')->get();
        return view('transaction_form', compact('users'));
    }

    /**
     * Show the form for creating a new transaction with predefined values.
     *
     * @param Transaction $oldTransaction
     * @return \Illuminate\Http\Response
     */
    public function duplicate(Transaction $transaction)
    {
        $users = User::where('id', '!=', auth()->user()->id)->orderBy('name')->get();
        return view('transaction_form', compact('users', 'transaction'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateTransactionRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTransactionRequest $request)
    {
        DB::transaction(function () use ($request) {
            $sender = auth()->user();
            $sender->balance = $sender->balance - $request->amount;
            $sender->save();

            $receiver = User::find($request->receiver_id);
            $receiver->balance = $receiver->balance + $request->amount;
            $receiver->save();

            $transaction['sender_id'] = $sender->id;
            $transaction['receiver_id'] = $receiver->id;
            $transaction['amount'] = $request->amount;
            $transaction['sender_balance'] = $sender->balance;
            $transaction['receiver_balance'] = $receiver->balance;

            Transaction::create($transaction);
        });

        \Session::flash('message', 'The transaction has been made successfully!');
        return redirect('/history');
    }

    /**
     * Cancel the transaction.
     *
     * @param  Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        DB::transaction(function () use ($transaction) {
            $transaction->delete();

            $sender = User::find($transaction->sender_id);
            $sender->balance = $sender->balance + $transaction->amount;
            $sender->save();

            $receiver = User::find($transaction->receiver_id);
            $receiver->balance = $receiver->balance - $transaction->amount;
            $receiver->save();
        });
        \Session::flash('message', 'The transaction has been successfully canceled!');
        return redirect('/admin/transactions');
    }
}

resources/views/admin/transactions/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2 class="display-4">Transactions History</h2>
        <div class="table-responsive-md">
            <table id="dtBasicExample" class="table table-bordered" >
                <thead>
                <tr>
                    <th class="th-sm" >#
                    </th>
                    <th class="th-sm" >Date/Time
                    </th>
                    <th class="th-sm">Sender Name
                    </th>
                    <th class="th-sm">Receiver Name
                    </th>
                    <th class="th-sm">Transaction Amount
                    </th>
                    <th class="th-sm">Sender Balance
                    </th>
                    <th class="th-sm">Receiver Balance
                    </th>
                    <th class="th-sm">Actions
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach($transactions as $transaction)
                    <tr class="{{$transaction->trashed() ? "table-warning" : ""}}">
                        <td>{{ $transaction->id }}</td>
                        <td>{{ $transaction->created_at }}</td>
                        <td>{{ $transaction->sender->name }}</td>
                        <td>{{ $transaction->receiver->name }}</td>
                        <td>{{ $transaction->amount }} PW</td>
                        <td>{{ $transaction->sender_balance }} PW</td>
                        <td>{{ $transaction->receiver_balance }} PW</td>
                        <td>
                            @if(!$transaction->trashed())
                                <a href="#" class="btn btn-sm btn-danger" onclick="event.preventDefault();
                                        document.getElementById('cancel-form-{{ $transaction->id }}').submit();"><i class="fa fa-times-circle mr-1"></i> Cancel</a>
                                <form id="cancel-form-{{ $transaction->id }}" action="{{route('admin.transactions.cancel', $transaction->id)}}" method="POST" style="display: none;">
                                    @csrf
                                    @method('DELETE')
                                </form>
                                @else
                                Canceled
                            @endif
                        </td>
                    </tr>

                @endforeach
                </tbody>
                <tfoot>
                <tr>
                    <th class="th-sm">#
                    </th>
                    <th class="th-sm">Date/Time
                    </th>
                    <th class="th-sm">Sender Name
                    </th>
                    <th class="th-sm">Receiver Name
                    </th>
                    <th class="th-sm">Transaction Amount
                    </th>
                    <th class="th-sm">Sender Balance
                    </th>
                    <th class="th-sm">Receiver Balance
                    </th>
                    <th class="th-sm">Actions
                    </th>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function () {
            $('#dtBasicExample').DataTable({
                "order": [],
                "columnDefs": [
                    { "orderable": false, "targets": 7 },
                    { "searchable": false, "targets": 7 }
                ]
            });
            $('.dataTables_length').addClass('bs-select');
        });
    </script>
@endsection