routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::get('history', 'TransactionController@history')->name('history');
    Route::get('balance', 'UserController@getBalance')->name('balance');
    Route::get('newTransaction', 'TransactionController@create')->name('newTransaction');
    Route::get('duplicate/{transaction}', 'TransactionController@duplicate')->name('duplicate');
    Route::post('transaction', 'TransactionController@store')->name('transaction');

    Route::group(['as' => 'admin.', 'prefix' => 'admin', 'middleware' => 'admin'], function () {
        //Users
        Route::get('users', 'UserController@index')->name('users');
        Route::get('users/{user}/edit', 'UserController@edit')->name('user.edit');
        Route::delete('users/{user}', 'UserController@destroy')->name('user.ban');
        Route::post('users/{id}', 'UserController@restore')->name('user.restore');
        Route::put('users/{user}', 'UserController@update')->name('user.update');

        //Transactions
        Route::get('transactions', 'TransactionController@index')->name('transactions');
        Route::delete('transactions/{transaction}', 'TransactionController@destroy')->name('transactions.cancel');
    });
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use SoftDeletes,Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'balance'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role()
    {
        return $this->belongsTo('App\Role');
    }

    public function sentTransactions() {
        return $this->hasMany(Transaction::class, 'sender_id')->withTrashed();
    }

    public function receivedTransactions() {
        return $this->hasMany(Transaction::class, 'receiver_id')->withTrashed();
    }

    public function getTransactionsAttribute() {
        return $this->sentTransactions->merge($this->receivedTransactions)->sortByDesc('created_at')->values()->all();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserUpdateRequest;
use App\User;

class UserController extends Controller
{
    /**
     * Show the list of all users.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::withTrashed()->where('role_id', 2)->get();
        return view('admin.users.index', compact('users'));
    }

    /**
     * Show user edit fotm.
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update user details.
     *
     * @param  UserUpdateRequest  $request
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserUpdateRequest $request, User $user)
    {
        $data = $request->all();
        if($request->has('password')){
            $data['password'] = bcrypt($request->password);
        }
        $user->update($data);
        \Session::flash('message', 'The user has been updated successfully!');
        return redirect('/admin/users');
    }

    /**
     * Make the user banned.
     *
     * @param  User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        \Session::flash('message', 'The user has been banned successfully!');
        return redirect('/admin/users');
    }

    /**
     * Restore the user.
     *
     * @param  $id
     * @return \Illuminate\Http\Response
     */
    public function restore($id)
    {
        User::withTrashed()->where('id', $id)->restore();
        \Session::flash('message', 'The user has been restored successfully!');
        return redirect('/admin/users');
    }

    /**
     * Get the current balance of authenticated user
     *
     * @return string
     */
    public function getBalance(){
        return auth()->user()->balance;
    }
}

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit User Details</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('admin.user.update', $user->id) }}">
                            @csrf
                            @method('PUT')

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ $user->name }}" >

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">Email</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ $user->email }}" >

                                    @if ($errors->has('email'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" >

                                    @if ($errors->has('password'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="balance" class="col-md-4 col-form-label text-md-right">Balance</label>

                                <div class="col-md-6">
                                    <input id="balance" type="number" min="0.01" step="0.01" class="form-control{{ $errors->has('balance') ? ' is-invalid' : '' }}" name="balance" value="{{ $user->balance }}" >

                                    @if ($errors->has('balance'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('balance') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </div>
                            </div>


                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>

    </script>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h2 class="display-4">Users List</h2>
        <div class="table-responsive-md">
            <table id="dtBasicExample" class="table table-bordered" >
                <thead>
                <tr>
                    <th class="th-sm" >#
                    </th>
                    <th class="th-sm" >Name
                    </th>
                    <th class="th-sm">Email
                    </th>
                    <th class="th-sm">Balance
                    </th>
                    <th class="th-sm">Registration Date
                    </th>
                    <th class="th-sm">Actions
                    </th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->balance }} PW</td>
                        <td>{{ $user->created_at }}</td>
                        <td>
                            @if($user->trashed())
                                <a href="#" class="btn btn-sm btn-warning" onclick="event.preventDefault();
                                        document.getElementById('restore-form-{{ $user->id }}').submit();"><i class="fa fa-undo mr-1"></i> Restore</a>
                                <form id="restore-form-{{ $user->id }}" action="{{route('admin.user.restore', $user->id)}}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                                @else
                                <a href="{{route('admin.user.edit', $user->id)}}" class="btn btn-sm btn-primary"><i class="fa fa-edit mr-1"></i> Edit</a>
                                <a href="#" class="btn btn-sm btn-danger" onclick="event.preventDefault();
                                        document.getElementById('ban-form-{{ $user->id }}').submit();"><i class="fa fa-ban mr-1"></i> BAN</a>
                                <form id="ban-form-{{ $user->id }}" action="{{route('admin.user.ban', $user->id)}}" method="POST" style="display: none;">
                                    @csrf
                                    @method('DELETE')
                                </form>
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
                <tfoot>
                <tr>
                    <th class="th-sm" >#
                    </th>
                    <th class="th-sm" >Name
                    </th>
                    <th class="th-sm">Email
                    </th>
                    <th class="th-sm">Balance
                    </th>
                    <th class="th-sm">Registration Date
                    </th>
                    <th class="th-sm">Actions
                    </th>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function () {
            $('#dtBasicExample').DataTable({
                "order": [],
                "columnDefs": [
                    { "orderable": false, "targets": 5 },
                    { "searchable": false, "targets": 5 }
                ]
            });
            $('.dataTables_length').addClass('bs-select');
        });
    </script>
@endsection